### PR TITLE
added addon channel

### PR DESCRIPTION
**Pull request by JBurlison**
Would this support addon messages?

### CODE REVIEW

**Comment by JBurlison** [comment]
I dont have any way of building this FYI, I am a C# dev and there was no instructions on how to build the project, I hope this works. The intent is to use the bot as a router for addon messages

**Comment by fjaros** [comment]
hey James. it is very easy to compile & test the project - follow the "OR to compile yourself" section at the end of the readme. 
Also is 0xBE indeed the code for all supported expansions?

**Comment by JBurlison** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/shared/SharedDefines.h#L3154
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Miscellaneous/SharedDefines.h#L5642

looks like its always  been -1 or 0xFF

**Comment by JBurlison** [comment]
I guess my question is, is there anything else I need to add to make this work?

**Comment by JBurlison** [comment]
Thinking about it, it would be good to filter this by addon message. where would be an appropriate place to add that?

**Comment by JBurlison** [comment]
https://wowwiki-archive.fandom.com/wiki/Events_A-Z_(full_list)?oldid=1038399

CHAT_MSG_ADDON

my concern here is the arguments. It has a prefix meant to route and arg 3 as dis type and a sender

where do I enforce this?

**Comment by fjaros** [comment]
you'll need to test all that. to be honest i haven't looked at this code in a .. a number of years. but
https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/game/GamePacketHandler.scala#L572 here is the function to parse the packet which sends CHAT_MSG_* events. take note that this function might be different for different expansions. you'll need to implement, if necessary, functionality in all the handlers, not just the handler for vanilla wow.

**Comment by JBurlison** [comment]
Thanks I will take a look

**Comment by JBurlison** [comment]
Hey, I am getting the messages but its not passing it along, 

I dont know what to make of the first part:

 07 FF FF FF FF 7F {  D6 00 00 00 00 00 00 00 00 00 7F {  D6 00 00 00 00 00 8C 00 00 00

is the "channel" of the message
D  W  N  L  L  

seems to be a delimiter
09 

The actual message
 1  6  4  2  5  5  7  0  8  7  .  9  5  1  ,  S  P  E  L  L  _  A  U  R  A  _  R  E  M  O  V  E  D  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  A  4  C  A  0  ,  B  a  e  l  y  ,  1  3  0  4  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  A  4  C  A  0  ,  B  a  e  l  y  ,  1  3  0  4  ,  9  9  3  9  5  5  ,  T  i  t  a  n     S  c  r  o  l  l  :     K  h  a  z  '  g  o  r  o  t  h  ,  1  ,  B  U  F  F 

20:51:24.348 DEBUG w.g.GamePacketHandlerWotLK - RECV CHAT: 07 FF FF FF FF 7F {  D6 00 00 00 00 00 00 00 00 00 7F {  D6 00 00 00 00 00 8C 00 00 00 D  W  N  L  L  09 1  6  4  2  5  5  7  0  8  7  .  9  5  1  ,  S  P  E  L  L  _  A  U  R  A  _  R  E  M  O  V  E  D  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  A  4  C  A  0  ,  B  a  e  l  y  ,  1  3  0  4  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  A  4  C  A  0  ,  B  a  e  l  y  ,  1  3  0  4  ,  9  9  3  9  5  5  ,  T  i  t  a  n     S  c  r  o  l  l  :     K  h  a  z  '  g  o  r  o  t  h  ,  1  ,  B  U  F  F  00 00
20:51:24.349 DEBUG w.g.GamePacketHandlerWotLK - RECV CHAT: 07 FF FF FF FF 7F {  D6 00 00 00 00 00 00 00 00 00 7F {  D6 00 00 00 00 00 86 00 00 00 D  W  N  L  L  09 1  6  4  2  5  5  7  0  8  7  .  9  5  1  ,  S  P  E  L  L  _  A  U  R  A  _  R  E  M  O  V  E  D  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  A  4  C  A  0  ,  B  a  e  l  y  ,  1  3  0  4  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  A  4  C  A  0  ,  B  a  e  l  y  ,  1  3  0  4  ,  9  9  3  9  5  7  ,  T  i  t  a  n     S  c  r  o  l  l  :     E  o  n  a  r  ,  1  ,  B  U  F  F  00 00
20:51:15.052 DEBUG w.g.GamePacketHandlerWotLK - RECV CHAT: 07 FF FF FF FF 7F {  D6 00 00 00 00 00 00 00 00 00 7F {  D6 00 00 00 00 00 x  00 00 00 D  W  N  L  L  09 1  6  4  2  5  5  7  0  7  8  .  6  4  9  ,  S  P  E  L  L  _  H  E  A  L  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  6  7  B  7  F  ,  P  a  n  d  a  r  o  s  ,  1  2  9  7  ,  0  x  0  0  0  0  0  0  0  0  0  0  D  6  7  B  7  F  ,  P  a  n  d  a  r  o  s  ,  1  2  9  7  ,  2  6  9  8  0  ,  R  e  g  r  o  w  t  h  ,  8  ,  3  4  5  7  00 00

**Comment by JBurlison** [comment]
Oh. https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/game/GamePacketHandlerWotLK.scala#L127

**Comment by fjaros** [comment]
Exactly. Just look at that function and how it's parsing the bytes. the first byte is the message type which seems to be 0x07 so WHISPER. Then we have 4 bytes for language (-1 meaning not specified) then you have 8 bytes for the guid... and so on.
Looks like the "text" part of the message is DWNLL<TAB>1642557087.951,SPELL_AURA_REMOVED,...
One thing that I don't see is where you are supposed to figure out this is a CHAT_MSG_ADDON. Maybe what could help you is see how trinitycore actually composes a CHAT_MSG_ADDON.

**Comment by JBurlison** [comment]
Using the combat log as a test. It will be used to route commands to a mod.

**Comment by fjaros** [comment]
> Using the combat log as a test. It will be used to route commands to a mod.

oh I see. have you considered using just whispers or perhaps a channel message? i'm guessing you're distributing an addon that will be able to send these mod commands, which could do that also instead of sending an addon message. the only thing is how will you handle the authorization?

**Comment by JBurlison** [comment]
That's originally how I had it but the addon sends other information too like gear, talents and loot. It shows these messages in the chat and even worse Wow instant messanger.

**Comment by fjaros** [comment]
sounds like the effort to filter those out is around the same as making the addon chat messages work.

**Comment by JBurlison** [comment]
Hey! super close here, 
https://github.com/fjaros/wowchat/pull/65/files#diff-ee7228026c88892c501acfd9e7d2c9341e140b55faeda1d129673a398ab536e3

channel.wow.channel is always none for some reason. Sorry new to skala, any tips here?

**Comment by JBurlison** [comment]
chat {
  channels=[
    {
      direction=both
      wow {
        type=addon
        prefix="DWNLL"
        format="%message"
      }
      discord {
        channel=gamebot
        format="%message"
      }
    }
  ]
}

Line 133 is coming back none https://github.com/fjaros/wowchat/pull/65/files#diff-ee7228026c88892c501acfd9e7d2c9341e140b55faeda1d129673a398ab536e3
 any idea?

**Comment by JBurlison** [comment]
so I verified that its parsing it correctly but Global.discord.sendMessageFromWow is not processing it.

```
chat {
  channels=[
    {
      direction=both
      wow {
        type=addon
        prefix="DWNLL"
        format="%message"
      }
      discord {
        channel=gamebot
        format="%message"
      }
    }
  ]
}
```

**Comment by JBurlison** [comment]
Ok its working

image

**Comment by fjaros** [comment]
Thanks! At some point I do plan on revisiting this project and just doing some house keeping like updating the used libraries and so on. I'll keep this one in mind to clean up & merge when I do.

**Comment by JBurlison** [comment]
Hey Do you think you could add an option to route to a TCP socket as well as discord too?

I was trying to figure it out but honestly im stuck.

**Comment by fjaros** [comment]
Yeah of course that's possible but obviously there is no framework already in the project to do that. Best advice I could offer is for you to search how to use netty.io (the Java networking library I chose to use at the time) to create a TCP connection and send data out. The bot already uses it to establish a TCP connection with the wow servers so you can probably get some help from reading that code. Look at classes RealmConnector and GameConnector

**Pull request closed without merging**
